feature {
  name: "activity"
  value_count {
    min: 1
    max: 1
  }
  type: BYTES
  domain: "activity"
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "timestamp"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "user_id"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "x-acc"
  value_count {
    min: 1
    max: 1
  }
  type: FLOAT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "y-acc"
  value_count {
    min: 1
    max: 1
  }
  type: FLOAT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "z-acc"
  value_count {
    max: 1
  }
  type: FLOAT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
string_domain {
  name: "activity"
  value: "Downstairs"
  value: "Jogging"
  value: "Sitting"
  value: "Standing"
  value: "Upstairs"
  value: "Walking"
}
